export const SAMPLE_ACTION = 'SAMPLE_ACTION'

export const USER_REGISTRATION_START = `USER_REGISTRATION_START`
export const USER_REGISTRATION_SUCCESS = `USER_REGISTRATION_SUCCESS`
export const USER_REGISTRATION_ERROR = `USER_REGISTRATION_ERROR`
export const USER_FETCH_LOCAL = `USER_FETCH_LOCAL`

export const CATEGORY_FETCH = `CATEGORY_FETCH`
export const CATEGORY_ADD = `CATEGORY_ADD`
export const CATEGORY_SAVE = `CATEGORY_SAVE`
export const CATEGORY_DELETE = `CATEGORY_DELETE`

export const GENERAL_LOADER_START = `GENERAL_LOADER_START`
export const GENERAL_LOADER_STOP = `GENERAL_LOADER_STOP`

export const EXPENSE_FETCH = `EXPENSE_FETCH`
export const EXPENSE_ADD = `EXPENSE_ADD`